raw_directory: /path/to/directory
segments_directory: /path/to/directory
work_directory: /path/to/directory
ready_directory: /path/to/directory
audio: /path/to/file

duration: 2
bpm: null
delete_work_dir: false
offset: 0
force: null
segment_duration: 2
segment_start: 0
segment_end: 0
force_segment: false
