paths:
  raw: /path/to/directory
  segments: /path/to/directory
  work: /path/to/directory
  ready: /path/to/directory

default:
  audio:
    file: /path/to/file
  segments:
    duration: 2
    start: 0
    end: 0
    force: 0
  work:
    duration: 2
    force: 0
    delete: 1
