duration: 2
audio: F:/projects/video/video/audio/cut_Jason Risk & Jacob Rodi - JUMP, JUMP!  (Original Mix)-v3zaUpZY4NM.webm
bpm: null
delete_work_dir: false
offset: 0
force: false
start: 1
end: 1
src_directory: F:/projects/video/video/files/src
work_directory: F:/projects/video/video/files/work
ready_directory: F:/projects/video/video/files/ready
convert: false
