paths:
  raw: /path/to/folder
  segments: /path/to/folder
  work: /path/to/folder
  ready: /path/to/folder

default:
  audio:
    file: /path/to/file
  segments:
    duration: 2
    start: 0
    end: 0
    force: 0
  work:
    duration: 2
    force: 0
    delete: 1
